apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: WEB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WEB
  template:
    metadata:
      labels:
        app: WEB
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always