#database.url=jdbc:postgresql://localhost:5432/postgres
#database.username=username
#database.password=password
#database.driver=org.postgresql.Driver
#database.port=5432
#database.schema=public

server:
  port: 8080
  ssl:
    enabled: false

bot:
  name: AutoGeek
  version: 0.1b
  token: 7337091756:AAGC1UQRpmA7iDTDFXXr7MI2g9TqC10DRhQ
  uri: https://7965-213-21-222-59.ngrok-free.app
  path: "/update"
  adminChatId: 8131369777
  supportChatId: 403438777


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace