spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=gpt-4o
# This ensures Spring pulls the model if you don't have it yet
spring.ai.ollama.chat.options.pull-model-strategy=when_missing