INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('895', 'Abkhazia', 'AB', 'ABH');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('036', 'Australia', 'AU', 'AUS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('040', 'Austria', 'AT', 'AUT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('031', 'Azerbaijan', 'AZ', 'AZE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('008', 'Albania', 'AL', 'ALB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('012', 'Algeria', 'DZ', 'DZA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('016', 'American Samoa', 'AS', 'ASM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('660', 'Anguilla', 'AI', 'AIA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('024', 'Angola', 'AO', 'AGO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('020', 'Andorra', 'AD', 'AND');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('028', 'Antigua and Barbuda', 'AG', 'ATG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('032', 'Argentina', 'AR', 'ARG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('051', 'Armenia', 'AM', 'ARM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('533', 'Aruba', 'AW', 'ABW');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('004', 'Afghanistan', 'AF', 'AFG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('044', 'Bahamas', 'BS', 'BHS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('050', 'Bangladesh', 'BD', 'BGD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('052', 'Barbados', 'BB', 'BRB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('048', 'Bahrain', 'BH', 'BHR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('112', 'Belarus', 'BY', 'BLR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('084', 'Belize', 'BZ', 'BLZ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('056', 'Belgium', 'BE', 'BEL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('204', 'Benin', 'BJ', 'BEN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('060', 'Bermuda', 'BM', 'BMU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('100', 'Bulgaria', 'BG', 'BGR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('068', 'Bolivia, plurinational state of', 'BO', 'BOL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('535', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('070', 'Bosnia and Herzegovina', 'BA', 'BIH');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('072', 'Botswana', 'BW', 'BWA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('076', 'Brazil', 'BR', 'BRA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('086', 'British Indian Ocean Territory', 'IO', 'IOT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('096', 'Brunei Darussalam', 'BN', 'BRN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('854', 'Burkina Faso', 'BF', 'BFA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('108', 'Burundi', 'BI', 'BDI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('064', 'Bhutan', 'BT', 'BTN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('548', 'Vanuatu', 'VU', 'VUT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('348', 'Hungary', 'HU', 'HUN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('862', 'Venezuela', 'VE', 'VEN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('092', 'Virgin Islands, British', 'VG', 'VGB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('850', 'Virgin Islands, U.S.', 'VI', 'VIR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('704', 'Vietnam', 'VN', 'VNM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('266', 'Gabon', 'GA', 'GAB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('332', 'Haiti', 'HT', 'HTI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('328', 'Guyana', 'GY', 'GUY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('270', 'Gambia', 'GM', 'GMB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('288', 'Ghana', 'GH', 'GHA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('312', 'Guadeloupe', 'GP', 'GLP');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('320', 'Guatemala', 'GT', 'GTM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('324', 'Guinea', 'GN', 'GIN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('624', 'Guinea-Bissau', 'GW', 'GNB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('276', 'Germany', 'DE', 'DEU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('831', 'Guernsey', 'GG', 'GGY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('292', 'Gibraltar', 'GI', 'GIB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('340', 'Honduras', 'HN', 'HND');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('344', 'Hong Kong', 'HK', 'HKG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('308', 'Grenada', 'GD', 'GRD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('304', 'Greenland', 'GL', 'GRL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('300', 'Greece', 'GR', 'GRC');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('268', 'Georgia', 'GE', 'GEO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('316', 'Guam', 'GU', 'GUM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('208', 'Denmark', 'DK', 'DNK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('832', 'Jersey', 'JE', 'JEY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('262', 'Djibouti', 'DJ', 'DJI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('212', 'Dominica', 'DM', 'DMA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('214', 'Dominican Republic', 'DO', 'DOM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('818', 'Egypt', 'EG', 'EGY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('894', 'Zambia', 'ZM', 'ZMB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('732', 'Western Sahara', 'EH', 'ESH');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('716', 'Zimbabwe', 'ZW', 'ZWE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('376', 'Israel', 'IL', 'ISR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('356', 'India', 'IN', 'IND');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('360', 'Indonesia', 'ID', 'IDN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('400', 'Jordan', 'JO', 'JOR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('368', 'Iraq', 'IQ', 'IRQ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('364', 'Iran, Islamic Republic of', 'IR', 'IRN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('372', 'Ireland', 'IE', 'IRL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('352', 'Iceland', 'IS', 'ISL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('724', 'Spain', 'ES', 'ESP');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('380', 'Italy', 'IT', 'ITA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('887', 'Yemen', 'YE', 'YEM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('132', 'Cape Verde', 'CV', 'CPV');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('398', 'Kazakhstan', 'KZ', 'KAZ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('116', 'Cambodia', 'KH', 'KHM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('120', 'Cameroon', 'CM', 'CMR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('124', 'Canada', 'CA', 'CAN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('634', 'Qatar', 'QA', 'QAT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('404', 'Kenya', 'KE', 'KEN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('196', 'Cyprus', 'CY', 'CYP');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('417', 'Kyrgyzstan', 'KG', 'KGZ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('296', 'Kiribati', 'KI', 'KIR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('156', 'China', 'CN', 'CHN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('166', 'Cocos (Keeling) Islands', 'CC', 'CCK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('170', 'Colombia', 'CO', 'COL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('174', 'Comoros', 'KM', 'COM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('178', 'Congo', 'CG', 'COG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('180', 'Congo, Democratic Republic of the', 'CD', 'COD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('408', 'Korea, Democratic People''s republic of', 'KP', 'PRK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('410', 'Korea, Republic of', 'KR', 'KOR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('188', 'Costa Rica', 'CR', 'CRI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('384', 'Cote d''Ivoire', 'CI', 'CIV');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('192', 'Cuba', 'CU', 'CUB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('414', 'Kuwait', 'KW', 'KWT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('531', 'Curaçao', 'CW', 'CUW');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('418', 'Lao People''s Democratic Republic', 'LA', 'LAO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('428', 'Latvia', 'LV', 'LVA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('426', 'Lesotho', 'LS', 'LSO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('422', 'Lebanon', 'LB', 'LBN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('434', 'Libyan Arab Jamahiriya', 'LY', 'LBY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('430', 'Liberia', 'LR', 'LBR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('438', 'Liechtenstein', 'LI', 'LIE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('440', 'Lithuania', 'LT', 'LTU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('442', 'Luxembourg', 'LU', 'LUX');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('480', 'Mauritius', 'MU', 'MUS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('478', 'Mauritania', 'MR', 'MRT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('450', 'Madagascar', 'MG', 'MDG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('175', 'Mayotte', 'YT', 'MYT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('446', 'Macao', 'MO', 'MAC');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('454', 'Malawi', 'MW', 'MWI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('458', 'Malaysia', 'MY', 'MYS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('466', 'Mali', 'ML', 'MLI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('581', 'United States Minor Outlying Islands', 'UM', 'UMI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('462', 'Maldives', 'MV', 'MDV');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('470', 'Malta', 'MT', 'MLT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('504', 'Morocco', 'MA', 'MAR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('474', 'Martinique', 'MQ', 'MTQ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('584', 'Marshall Islands', 'MH', 'MHL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('484', 'Mexico', 'MX', 'MEX');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('583', 'Micronesia, Federated States of', 'FM', 'FSM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('508', 'Mozambique', 'MZ', 'MOZ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('498', 'Moldova', 'MD', 'MDA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('492', 'Monaco', 'MC', 'MCO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('496', 'Mongolia', 'MN', 'MNG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('500', 'Montserrat', 'MS', 'MSR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('104', 'Burma', 'MM', 'MMR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('516', 'Namibia', 'NA', 'NAM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('520', 'Nauru', 'NR', 'NRU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('524', 'Nepal', 'NP', 'NPL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('562', 'Niger', 'NE', 'NER');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('566', 'Nigeria', 'NG', 'NGA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('528', 'Netherlands', 'NL', 'NLD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('558', 'Nicaragua', 'NI', 'NIC');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('570', 'Niue', 'NU', 'NIU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('554', 'New Zealand', 'NZ', 'NZL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('540', 'New Caledonia', 'NC', 'NCL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('578', 'Norway', 'NO', 'NOR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('784', 'United Arab Emirates', 'AE', 'ARE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('512', 'Oman', 'OM', 'OMN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('074', 'Bouvet Island', 'BV', 'BVT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('833', 'Isle of Man', 'IM', 'IMN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('574', 'Norfolk Island', 'NF', 'NFK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('162', 'Christmas Island', 'CX', 'CXR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('334', 'Heard Island and McDonald Islands', 'HM', 'HMD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('136', 'Cayman Islands', 'KY', 'CYM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('184', 'Cook Islands', 'CK', 'COK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('796', 'Turks and Caicos Islands', 'TC', 'TCA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('586', 'Pakistan', 'PK', 'PAK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('585', 'Palau', 'PW', 'PLW');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('275', 'Palestinian Territory, Occupied', 'PS', 'PSE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('591', 'Panama', 'PA', 'PAN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('336', 'Holy See (Vatican City State)', 'VA', 'VAT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('598', 'Papua New Guinea', 'PG', 'PNG');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('600', 'Paraguay', 'PY', 'PRY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('604', 'Peru', 'PE', 'PER');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('612', 'Pitcairn', 'PN', 'PCN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('616', 'Poland', 'PL', 'POL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('620', 'Portugal', 'PT', 'PRT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('630', 'Puerto Rico', 'PR', 'PRI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('807', 'Macedonia, The Former Yugoslav Republic Of', 'MK', 'MKD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('638', 'Reunion', 'RE', 'REU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('643', 'Russian Federation', 'RU', 'RUS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('646', 'Rwanda', 'RW', 'RWA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('642', 'Romania', 'RO', 'ROU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('882', 'Samoa', 'WS', 'WSM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('674', 'San Marino', 'SM', 'SMR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('678', 'Sao Tome and Principe', 'ST', 'STP');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('682', 'Saudi Arabia', 'SA', 'SAU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('654', 'Saint Helena, Ascension And Tristan Da Cunha', 'SH', 'SHN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('580', 'Northern Mariana Islands', 'MP', 'MNP');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('652', 'Saint Barthélemy', 'BL', 'BLM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('663', 'Saint Martin (French Part)', 'MF', 'MAF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('686', 'Senegal', 'SN', 'SEN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('670', 'Saint Vincent and the Grenadines', 'VC', 'VCT');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('659', 'Saint Kitts and Nevis', 'KN', 'KNA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('662', 'Saint Lucia', 'LC', 'LCA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('666', 'Saint Pierre and Miquelon', 'PM', 'SPM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('688', 'Serbia', 'RS', 'SRB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('690', 'Seychelles', 'SC', 'SYC');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('702', 'Singapore', 'SG', 'SGP');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('534', 'Sint Maarten', 'SX', 'SXM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('760', 'Syrian Arab Republic', 'SY', 'SYR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('703', 'Slovakia', 'SK', 'SVK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('705', 'Slovenia', 'SI', 'SVN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('826', 'United Kingdom', 'GB', 'GBR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('840', 'United States', 'US', 'USA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('090', 'Solomon Islands', 'SB', 'SLB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('706', 'Somalia', 'SO', 'SOM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('729', 'Sudan', 'SD', 'SDN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('740', 'Surifull_name', 'SR', 'SUR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('694', 'Sierra Leone', 'SL', 'SLE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('762', 'Tajikistan', 'TJ', 'TJK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('764', 'Thailand', 'TH', 'THA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('158', 'Taiwan, Province of China', 'TW', 'TWN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('834', 'Tanzania, United Republic Of', 'TZ', 'TZA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('626', 'Timor-Leste', 'TL', 'TLS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('768', 'Togo', 'TG', 'TGO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('772', 'Tokelau', 'TK', 'TKL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('776', 'Tonga', 'TO', 'TON');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('780', 'Trinidad and Tobago', 'TT', 'TTO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('798', 'Tuvalu', 'TV', 'TUV');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('788', 'Tunisia', 'TN', 'TUN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('795', 'Turkmenistan', 'TM', 'TKM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('792', 'Turkey', 'TR', 'TUR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('800', 'Uganda', 'UG', 'UGA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('860', 'Uzbekistan', 'UZ', 'UZB');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('804', 'Ukraine', 'UA', 'UKR');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('876', 'Wallis and Futuna', 'WF', 'WLF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('858', 'Uruguay', 'UY', 'URY');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('234', 'Faroe Islands', 'FO', 'FRO');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('242', 'Fiji', 'FJ', 'FJI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('608', 'Philippines', 'PH', 'PHL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('246', 'Finland', 'FI', 'FIN');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('238', 'Falkland Islands (Malvinas)', 'FK', 'FLK');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('250', 'France', 'FR', 'FRA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('254', 'French Guiana', 'GF', 'GUF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('258', 'French Polynesia', 'PF', 'PYF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('260', 'French Southern Territories', 'TF', 'ATF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('191', 'Croatia', 'HR', 'HRV');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('140', 'Central African Republic', 'CF', 'CAF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('148', 'Chad', 'TD', 'TCD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('499', 'Montenegro', 'ME', 'MNE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('203', 'Czech Republic', 'CZ', 'CZE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('152', 'Chile', 'CL', 'CHL');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('756', 'Switzerland', 'CH', 'CHE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('752', 'Sweden', 'SE', 'SWE');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('744', 'Svalbard and Jan Mayen', 'SJ', 'SJM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('144', 'Sri Lanka', 'LK', 'LKA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('218', 'Ecuador', 'EC', 'ECU');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('226', 'Equatorial Guinea', 'GQ', 'GNQ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('248', 'Åland Islands', 'AX', 'ALA');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('222', 'El Salvador', 'SV', 'SLV');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('232', 'Eritrea', 'ER', 'ERI');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('748', 'Eswatini', 'SZ', 'SWZ');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('233', 'Estonia', 'EE', 'EST');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('231', 'Ethiopia', 'ET', 'ETH');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('710', 'South Africa', 'ZA', 'ZAF');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('239', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('896', 'South Ossetia', 'OS', 'OST');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('728', 'South Sudan', 'SS', 'SSD');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('388', 'Jamaica', 'JM', 'JAM');
INSERT INTO public.countries (code, full_name, alpha2, alpha3) VALUES ('392', 'Japan', 'JP', 'JPN');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('1', 'Volkswagen Auto Group (VAG)', '276');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('2', 'Mercedes-Benz Group (Daimler)', '276');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('3', 'BMW Group', '276');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('4', 'Renault Group ', '250');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('5', 'Toyota Motor Corporation', '392');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('6', 'Honda Motor Co., Ltd.', '392');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('7', 'Hyundai Motor Company', '408');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('8', 'SAIC Motor ', '156');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('9', 'General Motors', '840');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('10', 'Ford Motor Company', '840');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('11', 'Stellantis', '840');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('12', 'Innoson Vehicle Manufacturing', '566');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('13', 'Kantanka Automobile', '288');
-- INSERT INTO public.concerns (id, full_name, country_code) VALUES ('14', 'Kiira Motors Corporation', '800');
