package ru.yanes.autoprom.enums;

public enum BodyType { CABRIOLET, COUPE, CONVERTIBLE,
	CROSSOVER, HATCHBACK, LIMOUSINE,
	LIFTBACK, MICRO, MINIVAN,
	MUSCLE,	OFFROAD, PICKUP,
	ROADSTER, SEDAN, SPORT,
	SUV, VAN, WAGON
}
